-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgEPdLJL/TkYdPsc32
XTVVA/QXa/6Y+76w8PZSFKkFhKOgCgYIKoZIzj0DAQehRANCAATyuOyo2/MLXoNg
s70+g2NuERoDJe1oDcwXp9XtpJj79ZxwCGTKX7phCUAFIUqAwzoPTgOTIvHHWd37
8xyHKP+6
-----END PRIVATE KEY-----